# Generated by Django 5.2 on 2025-04-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactmessages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='contact',
            new_name='contact_info',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
    ]
