# Generated by Django 5.2 on 2025-04-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_news_options_remove_news_date_news_date_posted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100, verbose_name='Telefon raqam yoki Email')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
