# Generated by Django 5.2 on 2025-04-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('subject', models.CharField(max_length=100, verbose_name='Fan')),
                ('bio', models.TextField(verbose_name="Qisqacha ma'lumot")),
                ('photo', models.ImageField(upload_to='teacher_photos/', verbose_name='Rasm')),
            ],
            options={
                'verbose_name': 'Ustoz',
                'verbose_name_plural': 'Ustozlar',
            },
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
