# Generated by Django 5.2 on 2025-04-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_teacher_delete_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='Dislike soni'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Like soni'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bio',
            field=models.TextField(verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Fan'),
        ),
    ]
