# Generated by Django 5.2 on 2025-04-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_teacher_dislikes_teacher_likes_alter_teacher_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='likes',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Fan'),
        ),
    ]
