# Generated by Django 5.2 on 2025-05-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_teacher_bio_remove_teacher_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
