# Generated by Django 5.2 on 2025-05-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_leadership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadership',
            options={'ordering': ['order'], 'verbose_name': 'Xodim', 'verbose_name_plural': 'Rahbarlar'},
        ),
        migrations.AddField(
            model_name='leadership',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
